[package]
name = "intellij-patch"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "intellij-patch"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
serde.workspace = true
shellexpand.workspace = true
skagedal-dirs.workspace = true
toml.workspace = true
xmltree.workspace = true

[dev-dependencies]
tempfile.workspace = true
