[package]
name = "gh-pr"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "gh-pr"
path = "src/main.rs"

[[bin]]
name = "mock-gh"
path = "src/bin/mock-gh.rs"

[[bin]]
name = "mock-git"
path = "src/bin/mock-git.rs"

[dependencies]
clap.workspace = true
opener = "0.7"

[dev-dependencies]
tempfile.workspace = true
