[package]
name = "rust-log-viewer"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rust-log-viewer"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.28"
ratatui = "0.29"
serde_json = { version = "1", features = ["preserve_order"] }
