[package]
name = "assistant"
version = "0.1.0"
authors = [""]
edition = "2024"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
serde.workspace = true
serde_yaml = "*"
regex.workspace = true
filetime = "*"
chrono = "*"
shellexpand = "*"
dirs = "*"
flexi_logger = "*"
log = "*"
once_cell = "*"
