[package]
name = "assistant"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap.workspace = true
clap_complete.workspace = true
serde.workspace = true
serde_yaml_ng = "*"
regex.workspace = true
filetime = "*"
chrono = "*"
shellexpand = "*"
dirs = "*"
flexi_logger = "*"
log = "*"
once_cell = "*"
