/// The bells Jikido can strike.
///
/// Each asset holds a complete three-strike sequence rather than a single
/// strike. Three strikes open a period of zazen and three close it, and
/// pre-rendering the whole sequence means the ring of one strike overlaps the
/// next exactly as it does on a real bell — and, more practically, that
/// ringing is a single `play()` with no timers of our own in between.
///
/// The assets are generated by `tool/synthesize_bells.py`; the durations
/// below must match what that script produces.
enum Bell {
  /// A small hand bell on a stick. Bright, quick to fade. This is the bell
  /// most zendos use to open and close a sitting.
  inkin(
    label: 'Inkin',
    description: 'Small hand bell — bright and clear',
    fileName: 'inkin',
    duration: Duration(seconds: 12),
  ),

  /// The large standing bowl gong. Low, and it rings for a long time.
  keisu(
    label: 'Keisu',
    description: 'Large bowl gong — deep and long',
    fileName: 'keisu',
    duration: Duration(seconds: 26),
  );

  const Bell({
    required this.label,
    required this.description,
    required this.fileName,
    required this.duration,
  });

  final String label;
  final String description;

  /// The stem shared by every copy of this bell: the Flutter asset, the
  /// Android `res/raw` resource and the iOS bundle resource are all named
  /// after it. Keep them in step when adding a bell.
  final String fileName;

  /// How long the three-strike sequence rings for, tail included.
  final Duration duration;

  /// Path of the bundled Flutter asset.
  String get assetPath => 'assets/audio/$fileName.wav';

  /// Name of the `android/app/src/main/res/raw` resource, which Android
  /// notification channels refer to without an extension.
  String get androidResourceName => fileName;

  /// Name of the resource in the iOS app bundle. Unlike Android, this one
  /// keeps its extension.
  String get iosSoundFile => '$fileName.wav';

  static Bell fromName(String? name) =>
      values.firstWhere((bell) => bell.name == name, orElse: () => inkin);
}
