import 'audio/bell_synth.dart';

/// The bells Jikido can strike.
///
/// A bell is an identity — a name, a description, and a pitch it sounds at
/// its default size. Everything audible about it is synthesized on the
/// device from that pitch; see `audio/bell_synth.dart`.
///
/// The file named by [fileName] is not what the app rings. It is only the
/// closing-bell notification, which the operating system plays when Jikido
/// has been killed and is not there to ring anything itself. That one has to
/// be a file on disk, so it is generated by `tool/synthesize_bells.py` and
/// always at the default size — a customized bell cannot be handed to the OS,
/// and this is a backstop for a case the user is not present for.
///
/// It is not a Flutter asset. A notification sound has to be a platform
/// resource, so it exists once under `android/app/src/main/res/raw` and once
/// in the iOS bundle, and nowhere else.
enum Bell {
  /// A small hand bell on a stick. Bright, quick to fade. This is the bell
  /// most zendos use to open and close a sitting.
  inkin(
    label: 'Inkin',
    description: 'Small hand bell — bright and clear',
    fileName: 'inkin',
    defaultDominantHz: 3245.0,
  ),

  /// The large standing bowl gong. Low, and it rings for a long time.
  keisu(
    label: 'Keisu',
    description: 'Large bowl gong — deep and long',
    fileName: 'keisu',
    defaultDominantHz: 500.0,
  );

  const Bell({
    required this.label,
    required this.description,
    required this.fileName,
    required this.defaultDominantHz,
  });

  final String label;
  final String description;

  /// The stem shared by every copy of the notification asset: the Flutter
  /// asset, the Android `res/raw` resource and the iOS bundle resource are
  /// all named after it. Keep them in step when adding a bell.
  final String fileName;

  /// The pitch this bell sounds at size 1.0, in Hz.
  ///
  /// The inkin's is the traditional inkin measured from the monastery-store
  /// demonstration. The keisu's is where a large standing bowl sits, and its
  /// half-minute of ring follows from that on its own.
  final double defaultDominantHz;

  /// This bell at [size]: 1.0 as it comes, smaller below, larger above.
  BellVoice voiceAt(double size) =>
      BellVoice(dominantHz: defaultDominantHz).scaled(size);

  /// How long three strikes ring for at [size], tail included.
  Duration openingRingAt(double size) => _seconds(openingSeconds(voiceAt(size)));

  /// How long the closing rings for at [size].
  ///
  /// Far shorter than [openingRingAt]: the closing ends with the striker laid
  /// on the bowl, so there is no tail to wait out. The sitting is over when
  /// this has elapsed.
  Duration closingRingAt(double size) => _seconds(closingSeconds(voiceAt(size)));

  /// Name of the `android/app/src/main/res/raw` resource, which Android
  /// notification channels refer to without an extension.
  String get androidResourceName => fileName;

  /// Name of the resource in the iOS app bundle. Unlike Android, this one
  /// keeps its extension.
  String get iosSoundFile => '$fileName.wav';

  static Bell fromName(String? name) =>
      values.firstWhere((bell) => bell.name == name, orElse: () => inkin);
}

Duration _seconds(double value) =>
    Duration(microseconds: (value * Duration.microsecondsPerSecond).round());
