[package]
name = "tracker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
clap_complete.workspace = true
chrono = "*"
# TODO: replace with etcetera
directories = "*"
num-traits = "*"
regex.workspace = true
serde.workspace = true
temp-dir = "*"
toml.workspace = true
etcetera = "*"
