[package]
name = "trafikverket"
version = "0.1.0"
edition.workspace = true

[[bin]]
name = "trafikverket"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
console.workspace = true
dialoguer.workspace = true
libc.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
skagedal-dirs.workspace = true
tokio.workspace = true
toml.workspace = true

[dev-dependencies]
chrono.workspace = true
serde_json.workspace = true
tempfile.workspace = true
