[package]
name = "simons-misc-helpers"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "simons-misc-helpers"
path = "src/main.rs"

[lib]
name = "simons_misc_helpers"
path = "src/lib.rs"

[dependencies]
anyhow = "*"
clap = { version = "*", features = ["derive"] }
crossterm = "*"
semver = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
